### ISSUE TITLE
Docker server repacking broken by template renaming

### ISSUE THREAD

**Issue by destijl** [google/grr#265]
The docker containers are being built OK but they don't run because the template repacking has been broken by the recent rename. The error is:
```
Failed to repack /usr/share/grr/executables/windows/templates/GRR_3.0.0.7_amd64.exe.zip
```
One problem is that the Dockerfile isn't copying the new config into /etc, so we're using the new code, but the old config that came from the .deb. The second problem is that the server deb has the old templates.

We should break the dependency on the server deb by downloading the templates and writing a quick script to do the various copying and init script starting that the package does for us. This will also be useful for people installing the server from source.

**Comment by cybercuffs** [comment]
I noticed the same issue so I had to rename the file to repack it.

**Comment by destijl** [comment]
Fixed in https://github.com/google/grr/commit/25ee38040644a334116fa7c3961f90241549b341

**Comment by cybercuffs** [comment]
Updated to 25ee380 but still getting the same error.

"Template /opt/grr/share/grr/executables/linux/templates/GRR_3.0.7.1_amd64.rpm.zip missing - will not repack. "

**Comment by 0xdabbad00** [comment]
I've been having the same issue today.  Looks like the files in https://googledrive.com/host/0B1wsLqFoT7i2VXBtSlJHRF9ycFU/ no longer have "client_" in their names.    This ultimately caused 
```
/usr/share/grr# grr_config_updater repack_clients
Using configuration <YamlParser filename="/etc/grr/grr-server.yaml">
Will repack the following clients :

Repacking : /usr/share/grr/executables/windows/templates/GRR_3.0.0.7_amd64.exe.zip (NOT READABLE)
To :        /usr/share/grr/executables/windows/installers/GRR_3.0.0.7_amd64.exe

...
```

So I renamed `/usr/share/grr/executables/darwin/templates/grr-client_3.0.0.7_amd64.pkg.xar` to `grr_3.0.0.7_amd64.pkg.xar` (since I just care about OSX right now) and when I reran the script that got me to:

```
/usr/share/grr/executables/darwin/templates/grr_3.0.0.7_amd64.pkg.xar repacked ok.
Traceback (most recent call last):
  File "/usr/local/bin/grr_config_updater", line 9, in <module>
    load_entry_point('grr==0.3.0-7', 'console_scripts', 'grr_config_updater')()
  File "/usr/local/lib/python2.7/dist-packages/grr-0.3.0_7-py2.7-linux-x86_64.egg/grr/lib/distro_entry.py", line 53, in ConfigUpdater
    flags.StartMain(config_updater.main)
  File "/usr/local/lib/python2.7/dist-packages/grr-0.3.0_7-py2.7-linux-x86_64.egg/grr/lib/flags.py", line 107, in StartMain
    main([sys.argv[0]])
  File "/usr/local/lib/python2.7/dist-packages/grr-0.3.0_7-py2.7-linux-x86_64.egg/grr/tools/config_updater.py", line 813, in main
    token=token)
  File "/usr/local/lib/python2.7/dist-packages/grr-0.3.0_7-py2.7-linux-x86_64.egg/grr/lib/maintenance_utils.py", line 284, in RepackAllBinaries
    UploadSignedConfigBlob(open(output_path).read(100 * 1024 * 1024),
MemoryError
```

So it seems I cleared that hurdle but now I'm trying to figure out if my VM actually ran out of memory or if there is another bug involved now.

**Comment by 0xdabbad00** [comment]
To give more context, I was just trying to run the docker image, as shown in this pastebin: http://pastebin.com/VTrUeWsg

I didn't look at that output unfortunately and only noticed there was a problem when I went to http://localhost:8000/#main=BinaryConfigurationView&ft=FlowInformation&t=_executables-darwin-installers and didn't see any files to download so I could install an agent.

**Comment by 0xdabbad00** [comment]
The rename did work, and I fixed my out of memory error by giving the VM more RAM, so my short-term workaround has worked.

**Comment by destijl** [comment]
@cybercuffs you need to download the new template.

@0xdabbad00 You need to pull the latest docker image that got built off the last commit. You are using an old config that has the old (3007) client version in it, but are using the new code, which is looking for a config starting with grr_*

There appears to be a problem with numpy as built on dockerhub (I didn't have this problem when I built the image on my own machine). Here's a working repack from the image on dockerhub:

```
$ docker run -it grrdocker/grr bash
root@39dee5485c1f:/usr/share/grr# pip install --upgrade numpy
/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
Collecting numpy
  Downloading numpy-1.10.0.post2.tar.gz (4.1MB)
    100% |################################| 4.1MB 113kB/s 
Building wheels for collected packages: numpy
  Running setup.py bdist_wheel for numpy
  Stored in directory: /root/.cache/pip/wheels/03/0e/e4/e3ba93fd71c3d129e7e4ea13c503b07f9c37e8114c47903edf
Successfully built numpy
Installing collected packages: numpy
  Found existing installation: numpy 1.9.1
    Uninstalling numpy-1.9.1:
      Successfully uninstalled numpy-1.9.1
Successfully installed numpy-1.10.0.post2

root@39dee5485c1f:/usr/share/grr# EXTERNAL_HOSTNAME="localhost" ADMIN_PASSWORD="demo" ./scripts/docker-entrypoint.sh grr
Checking write access on config <YamlParser filename="/etc/grr/grr-server.yaml">
All keys will have a bit length of 2048.
Generating executable signing key
.............................................................+++
....................................................................+++
Generating driver signing key
......................................................................................+++
...+++
Generating CA keys
Generating Server keys
Generating Django Secret key (used for xsrf protection etc)
Setting configuration as:

{'Logging.domain': 'localhost', 'Monitoring.emergency_access_email': 'grr-emergency@localhost', 'Monitoring.alert_email': 'grr-monitoring@localhost', 'Client.control_urls': ['http://localhost:8080/control'], 'Datastore.implementation': 'SqliteDataStore', 'AdminUI.url': 'http://localhost:8000'}
Configuration parameters set. You can edit these in /etc/grr/server.local.yaml

Step 3: Adding Admin User
Added user admin.

Step 4: Uploading Memory Drivers to the Database
Signing and uploading /usr/share/grr/binaries/OSXPMem-ng-signed.tar.gz to aff4:/config/drivers/osx/memory/pmem-ng-signed
uploaded aff4:/config/drivers/osx/memory/pmem-ng-signed
Signing and uploading /usr/share/grr/binaries/winpmem_i386_1.6.1.sys to aff4:/config/drivers/windows/memory/winpmem.x86.sys
uploaded aff4:/config/drivers/windows/memory/winpmem.x86.sys
Signing and uploading /usr/share/grr/binaries/winpmem_amd64_1.6.1.sys to aff4:/config/drivers/windows/memory/winpmem.amd64.sys
uploaded aff4:/config/drivers/windows/memory/winpmem.amd64.sys

Step 5: Repackaging clients with new configuration.
Will repack the following clients (debug build):

Repacking : /usr/share/grr/executables/windows/templates/GRR_3.0.7.1_amd64.exe.zip
To :        /usr/share/grr/executables/windows/installers/dbg_GRR_3.0.7.1_amd64.exe

Repacking : /usr/share/grr/executables/windows/templates/GRR_3.0.7.1_i386.exe.zip
To :        /usr/share/grr/executables/windows/installers/dbg_GRR_3.0.7.1_i386.exe

Repacking : /usr/share/grr/executables/linux/templates/grr_3.0.7.1_amd64.deb.zip
To :        /usr/share/grr/executables/linux/installers/dbg_grr_3.0.7.1_amd64.deb

Repacking : /usr/share/grr/executables/linux/templates/grr_3.0.7.1_i386.deb.zip
To :        /usr/share/grr/executables/linux/installers/dbg_grr_3.0.7.1_i386.deb

Repacking : /usr/share/grr/executables/linux/templates/grr_3.0.7.1_amd64.rpm.zip
To :        /usr/share/grr/executables/linux/installers/dbg_grr_3.0.7.1_amd64.rpm

Repacking : /usr/share/grr/executables/linux/templates/grr_3.0.7.1_i386.rpm.zip
To :        /usr/share/grr/executables/linux/installers/dbg_grr_3.0.7.1_i386.rpm

Repacking : /usr/share/grr/executables/darwin/templates/grr_3.0.7.1_amd64.pkg.xar
To :        /usr/share/grr/executables/darwin/installers/dbg_grr_3.0.7.1_amd64.pkg

/usr/share/grr/executables/windows/templates/GRR_3.0.7.1_amd64.exe.zip repacked ok.
/usr/share/grr/executables/windows/templates/GRR_3.0.7.1_i386.exe.zip repacked ok.
/usr/share/grr/executables/linux/templates/grr_3.0.7.1_amd64.deb.zip repacked ok.
/usr/share/grr/executables/linux/templates/grr_3.0.7.1_i386.deb.zip repacked ok.
/usr/share/grr/executables/linux/templates/grr_3.0.7.1_amd64.rpm.zip repacked ok.
/usr/share/grr/executables/linux/templates/grr_3.0.7.1_i386.rpm.zip repacked ok.
/usr/share/grr/executables/darwin/templates/grr_3.0.7.1_amd64.pkg.xar repacked ok.
Will repack the following clients :

Repacking : /usr/share/grr/executables/windows/templates/GRR_3.0.7.1_amd64.exe.zip
To :        /usr/share/grr/executables/windows/installers/GRR_3.0.7.1_amd64.exe

Repacking : /usr/share/grr/executables/windows/templates/GRR_3.0.7.1_i386.exe.zip
To :        /usr/share/grr/executables/windows/installers/GRR_3.0.7.1_i386.exe

Repacking : /usr/share/grr/executables/linux/templates/grr_3.0.7.1_amd64.deb.zip
To :        /usr/share/grr/executables/linux/installers/grr_3.0.7.1_amd64.deb

Repacking : /usr/share/grr/executables/linux/templates/grr_3.0.7.1_i386.deb.zip
To :        /usr/share/grr/executables/linux/installers/grr_3.0.7.1_i386.deb

Repacking : /usr/share/grr/executables/linux/templates/grr_3.0.7.1_amd64.rpm.zip
To :        /usr/share/grr/executables/linux/installers/grr_3.0.7.1_amd64.rpm

Repacking : /usr/share/grr/executables/linux/templates/grr_3.0.7.1_i386.rpm.zip
To :        /usr/share/grr/executables/linux/installers/grr_3.0.7.1_i386.rpm

Repacking : /usr/share/grr/executables/darwin/templates/grr_3.0.7.1_amd64.pkg.xar
To :        /usr/share/grr/executables/darwin/installers/grr_3.0.7.1_amd64.pkg

/usr/share/grr/executables/windows/templates/GRR_3.0.7.1_amd64.exe.zip repacked ok.
/usr/share/grr/executables/windows/templates/GRR_3.0.7.1_i386.exe.zip repacked ok.
/usr/share/grr/executables/linux/templates/grr_3.0.7.1_amd64.deb.zip repacked ok.
/usr/share/grr/executables/linux/templates/grr_3.0.7.1_i386.deb.zip repacked ok.
/usr/share/grr/executables/linux/templates/grr_3.0.7.1_amd64.rpm.zip repacked ok.
/usr/share/grr/executables/linux/templates/grr_3.0.7.1_i386.rpm.zip repacked ok.
/usr/share/grr/executables/darwin/templates/grr_3.0.7.1_amd64.pkg.xar repacked ok.

Initialization complete, writing configuration.
Please restart the service for it to take effect.


Admin UI gui is at http://localhost:8000, clients will poll to http://localhost:8080
```

**Comment by cybercuffs** [comment]
@destijl I did download the new clients from the https://f24b8c64b02bc5e251c0ab5c3bc910ebf481a89f.googledrive.com/host/0B1wsLqFoT7i2VXBtSlJHRF9ycFU/. It is expecting 'GRR' in the name and not 'grr'. When I manually changed it to 'GRR', it worked. Only windows clients that are uploaded has 'GRR' in their name so that looks fine. But windows client gives different error. 

    ERROR:2015-10-08 18:13:42,568 build:342] Build Config Error: Logging.path starts with /, probably has Unix path. /var/log/grr
    Repacking template /opt/grr/share/grr/executables/windows/templates/GRR_3.0.7.1_amd64.exe.zip failed: Bad configuration generated. Terminating.

**Comment by grrrrrrrrr** [comment]
I tried to repack the Windows client too and it seems to work - @cybercuffs, there seems to be something wrong with your config or maybe you have some version conflict. What GRR version are you using currently? https://github.com/google/grr/commit/ca16a4ca040e2b0c7bf5232d554bf2d4a3c74602 changed client building a bit, I'd suggest a version later than that.

There might also be config changes in /etc/grr/server.local.yaml. You'd probably know if you changed your logging there but maybe it's worth checking?

**Comment by destijl** [comment]
@cybercuffs the case is correct in drive. Windows is uppercase GRR, everything else is lowercase grr. You shouldn't have to rename anything. Agree with andy, it looks like there's a problem with your config. Diff against latest and check your server.local.yaml.

**Comment by cybercuffs** [comment]
Thanks. Looks like the issue was in /etc/grr/server.local.yaml. Just re-initializing is not enough. I had to delete the existing /etc/grr/server.local.yaml and re-initialize to have this fixed.
