### ISSUE TITLE
Another Grr Install Failure (sudo bash install_script_ubuntu.sh)

### ISSUE THREAD

**Issue by mrlong0124** [google/grr#332]
I am trying to install GRR on Ubuntu 14.04.3 using the install_script_ubuntu.sh script.

I get to the end of the install and receive the following message:

Run enable_services grr-http-server [Y/n/a]? Y
#### Running #### enable_services grr-http-server
Starting grr-http-server
initctl: Unknown job: grr-http-server
start: Unknown job: grr-http-server
#########################################################################################
FAILURE RUNNING: enable_services grr-http-server
#########################################################################################

I tried the fix using the commands below, but they don't seem to run:

. /usr/share/grr/scripts/shell_helpers.sh
enable_services grr-http-server
enable_services grr-ui
enable_services grr-worker

Nothing I do to fix this helps. Please assist!

**Comment by chumstick** [comment]
is it a clean box?

I only had this problem on US 15 since upstart was replaced.

**Comment by destijl** [comment]
Some background on the systemd problem:
https://github.com/google/grr-doc/issues/36

Can you try running the commands manually and post the output? Those scripts are just shortcuts for:

```
sudo service grr-worker start
```
and similar.  From your output it looks like the /etc/init/grr-* scripts might be missing?

**Comment by mrlong0124** [comment]
Its clean. I downloaded Ubuntu explicitly for this GRR installation. I tried it on both Ubuntu 14 and 15 and both gave me the same error. >_<

**Comment by chumstick** [comment]
Also, another thing is to make sure you have SSL installed, which was a pre-req during the ubuntu install I’ve seen people skip.

**Comment by mrlong0124** [comment]
I tried "sudo service grr-worker start", got 
grr_worker: unrecognized service

**Comment by destijl** [comment]
what's in /etc/init/grr-*?

**Comment by mrlong0124** [comment]
root@GRR-Ubuntu-x64:/etc/init# ls grr-*

grr-dataserver-master.conf  grr-http-server.conf  grr-worker.conf
grr-dataserver-slave.conf   grr-ui.conf

**Comment by pidydx** [comment]
Have you tried running 'initctl reload-configuration'?

I have run into this and it is addressed in this PR https://github.com/google/grr/pull/324/files#diff-f7ec1230b85470e7f9ac960f2abdaa72R97

**Comment by mrlong0124** [comment]
I just ran 'initctl reload-configuration', sadly it didn't fix the problem. Are there manual ways of starting GRR? I tried "service grr-http-server" but that doesn't work...

**Comment by destijl** [comment]
We install both /etc/init and /etc/init.d scripts so we can handle debian with the same package. We're shortly going to release a new server that deletes whichever one isn't needed in the package post-install. I suspect something with upstart has changed and it is now getting confused by having both present.

You could try using the /etc/init.d scripts instead, or if all else fails, just get the commands out of the scripts and run them manually.

**Comment by destijl** [comment]
and according to the manpage, the reload-configuration shouldn't be needed:

"This command is generally not necessary since init(8) watches its configuration directories with inotify(7) and automatically reloads in cases of changes."

**Comment by destijl** [comment]
I'm testing to see if the "unstable-28Jan2016_0.3.0-7" version from the install folder:
https://googledrive.com/host/0B1wsLqFoT7i2c3F0ZmI1RDJlUEU/

will install cleanly. If so I'll switch the script over to using that until we get the new release out. You can try this package out yourself in the meantime. You can also use the docker instructions if you just want a server for testing.

**Comment by destijl** [comment]
That worked, so try out that package. I have a change in review to update the script to use it automatically.

**Comment by destijl** [comment]
OK, so actually I can't reproduce this failure on a clean system. Here's what I did:

Start a new ubuntu trusty vm using vagrant
```
sudo apt-get update
sudo apt-get dist-upgrade
sudo reboot
vagrant@vagrant-ubuntu-trusty-64:~$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04.4 LTS"
wget https://raw.githubusercontent.com/google/grr/master/scripts/install_script_ubuntu.sh
sudo bash install_script_ubuntu.sh
```
Tons of output...

```
Initialization complete, writing configuration.
Please restart the service for it to take effect.



##########################################################################################
     Enable grr services to start automatically on boot
##########################################################################################
Starting grr-http-server
grr-http-server start/running, process 1868
Starting grr-ui
grr-ui start/running, process 1882
Starting grr-worker
grr-worker start/running, process 1896

##########################################################################################
     Install complete. Congratulations. Point your browser at http://vagrant-ubuntu-trusty-64:8000
##########################################################################################
vagrant@vagrant-ubuntu-trusty-64:~$ ps aux | grep grr
root      1868 20.1  7.5 1089808 153816 ?      Ssl  18:37   0:01 /usr/bin/python /usr/bin/grr_server --start_http_server --disallow_missing_config_definitions --config=/etc/grr grr-server.yaml
root      1882 19.6  7.5 1017292 155076 ?      Ssl  18:37   0:01 /usr/bin/python /usr/bin/grr_server --start_ui --disallow_missing_config_definitions --config=/etc/grr/grr-server.yaml
root      1896 22.6  7.6 1163092 157736 ?      Ssl  18:37   0:02 /usr/bin/python /usr/bin/grr_server --start_worker --disallow_missing_config_definitions --config=/etc/grr/grr-server.yaml
```

So I'm going to leave the package as is rather than switch to something that is less tested.

**Comment by schmiedecker** [comment]
Just a remark: this seems to happen on 15.10 (as well?), as install_bash_ubuntu.sh fails with the error message below and fails to create the .service files. Also, no grr-* files in /etc/init.d/


    Initialization complete, writing configuration.
    Please restart the service for it to take effect.
    
    
    
    ##########################################################################################
         Enable grr services to start automatically on boot
    ##########################################################################################
    Starting grr-http-server
    Failed to start grr-http-server.service: Unit grr-http-server.service failed to load: No such file or directory.
    #########################################################################################
    FAILURE RUNNING: enable_services grr-http-server
    #########################################################################################


If upstart is not installed there is just an additional line saying that initclt was not found

    /usr/share/grr/scripts/shell_helpers.sh: line 63: initctl: command not found


One can still start grr manually by running these commands:

    root@GRRserver:~# /usr/bin/grr_server --start_http_server --config=/etc/grr/grr-server.yaml
    root@GRRserver:~# /usr/bin/grr_server --start_ui --config=/etc/grr/grr-server.yaml
    root@GRRserver:~# /usr/bin/grr_server --start_worker --config=/etc/grr/grr-server.yaml
