### ISSUE TITLE
Landing page does not work due to JavaScript errors

### ISSUE THREAD

**Issue by zbuc** [google/grr#416]
Using the latest version of the Docker image (`6b9549ce3b49c56a7eb622f0515e706619e61a81ab78176b3e248b14ff91b4f3`) pulled fresh, no modifications, run using the instructions from the docs...

`docker run -e EXTERNAL_HOSTNAME="my.host" -e ADMIN_PASSWORD="demo" --ulimit nofile=1048576:1048576 -p 0.0.0.0:8000:8000 -p 0.0.0.0:8080:8080 grrdocker/grr:latest`

When I try loading https://my.host:8000, I see the HTML template for GRR load, but none of the JavaScript-driven content is rendered due to multiple JavaScript errors:

```
Navigated to http://www.my.host:8000/

third-party.bundle.js?timestamp=1469219453.23:11032 JQMIGRATE: Migrate is installed with logging active, version 1.4.1

grant-access-directive.js:3Uncaught ReferenceError: goog is not defined(anonymous function) @ grant-access-directive.js:3

(index):18 Uncaught ReferenceError: goog is not defined(anonymous function) @ (index):18

(index):21 Uncaught ReferenceError: grrUi is not defined(anonymous function) @ (index):21

third-party.bundle.js?timestamp=1469219453.23:14194 Uncaught Error: [$injector:modulerr] Failed to instantiate module grrUi due to:

Error: [$injector:modulerr] Failed to instantiate module grrUi.appController due to:

Error: [$injector:nomod] Module 'grrUi.appController' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
```

**Comment by zbuc** [comment]
Looks like an Angular JS file is in the wrong location on the filesystem:

a post-processed version of 

`/usr/src/grr/grr/gui/static/angular-components/acl/grant-access-directive.js`

should be present in

`/usr/share/grr-server/lib/python2.7/site-packages/grr/gui/static/dist/`

but is not

**Comment by destijl** [comment]
I reproduced this but it's not obvious what's wrong. Misha will take a look.

**Comment by mbushkov** [comment]
This is now fixed. Please try the latest docker image.

**Comment by jessicawilsonsc** [comment]
Still running into issues with the pip install. Upgraded to the newest commit, still showing the JS errors as the Docker image.

**Comment by mbushkov** [comment]
Jessica, does it work for you with the latest Docker image?
Does it help if you run "npm update; bower update; gulp compile" in
grr/gui/static?

Cheers,
Misha

**Comment by jessicawilsonsc** [comment]
That fixed it! Is this something that will need to be run every time I upgrade tracking HEAD with pip?

**Comment by mbushkov** [comment]
Usually you don't need to run this command (unless you're a developer
working on GRR UI code). Pip does it for you when building the package with
"pip install -e ."
How do you upgrade exactly? Do you run "pip install -e ." after you update
the sources?

Cheers,
Misha

**Comment by jessicawilsonsc** [comment]
Usually I pull the sources then run `python makefile.py` in `grr/`. However, if `pip install -e .` is best, I would be more than happy to switch to that.

**Comment by mbushkov** [comment]
python makefile.py just rebuild the protobufs, but doesn't rebuild the
JS/CSS files. "pip install -e ." does all that and should be a more
reliable solution.

Cheers,
Misha
