### ISSUE TITLE
Hunt manager doesn't show completed or pending clients, "n not a valid string"

### ISSUE THREAD

**Issue by devyzr** [google/grr#546]
Good afternoon,

I'm having an issue where the hunt manager is refusing to show the outstanding and completed clients and showing either **"2 not a valid string"** or **"n not a valid string"**, n being a 4 or 5 digit number.

The output of the error is the following:

```
Traceback (most recent call last):
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr/gui/http_api.py", line 474, in HandleRequest
    result = self.CallApiHandler(handler, args, token=token)
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr/gui/http_api.py", line 290, in CallApiHandler
    result = handler.Handle(args, token=token)
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr/gui/api_plugins/hunt.py", line 1129, in Handle
    self.IncludeRequestInformationInResults(hunt_urn, results, token=token)
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr/gui/api_plugins/hunt.py", line 1094, in IncludeRequestInformationInResults
    available_client_requests_count=client_requests_available)
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr/lib/rdfvalues/structs.py", line 1570, in __init__
    setattr(self, arg, value)
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr/lib/rdfvalues/structs.py", line 2200, in <lambda>
    lambda self, x: self._Set(x, field_desc), None,
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr/lib/rdfvalues/structs.py", line 1737, in _Set
    value = type_descriptor.Validate(value, container=self)
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr/lib/rdfvalues/structs.py", line 447, in Validate
    raise type_info.TypeValueError("%s not a valid string" % value)
TypeValueError: 2 not a valid string
```

**Comment by mbushkov** [comment]
Hi! Which version of GRR are you running?

**Comment by grrrrrrrrr** [comment]
We are asking because this is a known issue that we fixed in https://github.com/google/grr/commit/61ff0269a056a072181eaccba96304531d4fed6d#diff-faabab678392c414902c21ae03f64919R1121 on Sep 21. If you run a newer GRR server, this should not be a problem.

**Comment by devyzr** [comment]
I'm pretty sure I'm running 3.2.0.1, but to be sure I put the following in grr_console: 
```
import grr
grr.version()
```
returns
```
Out[8]:
{'major' : 3,
'minor' : 2,
'packageversion' : '3.2.0post1',
'release' : 1,
'revision' : 0}
```
I'm also sure I used the following .deb file for the install:

https://storage.googleapis.com/releases.grr-response.com/grr-server_3.2.0-1_amd64.deb

Isn't that the latest version?

**Comment by mbushkov** [comment]
Daniel, thanks for confirming the version. Seems like we still have the issue in 3.2.0.1. A few questions:
* Is the hunt new? I.e. it's not a hunt started on a previous version of GRR, right?
* What flow does the hunt run?

**Comment by devyzr** [comment]
> Is the hunt new? I.e. it's not a hunt started on a previous version of GRR, right?

It's a new hunt. GRR was installed on a fresh install of Debian. I don't know if this might be the culprit, but nothing other than the base system was installed on the system (aka, no CUPS, no UI and no standard system utilities), gnome-core was installed via apt.

> What flow does the hunt run?

```
Flow Name: FileFinder
Flow Arguments:
Paths |
    z:\**10{.exe,.dll,.zip,.vbs,.gz,.aspx,.php,.rar,.7z}
    y:\**10{.exe,.dll,.zip,.vbs,.gz,.aspx,.php,.rar,.7z}
    x:\**10{.exe,.dll,.zip,.vbs,.gz,.aspx,.php,.rar,.7z}
    w:\**10{.exe,.dll,.zip,.vbs,.gz,.aspx,.php,.rar,.7z}
    v:\**10{.exe,.dll,.zip,.vbs,.gz,.aspx,.php,.rar,.7z}
    u:\**10{.exe,.dll,.zip,.vbs,.gz,.aspx,.php,.rar,.7z}
    t:\**10{.exe,.dll,.zip,.vbs,.gz,.aspx,.php,.rar,.7z}
    s:\**10{.exe,.dll,.zip,.vbs,.gz,.aspx,.php,.rar,.7z}
    r:\**10{.exe,.dll,.zip,.vbs,.gz,.aspx,.php,.rar,.7z}
    q:\**10{.exe,.dll,.zip,.vbs,.gz,.aspx,.php,.rar,.7z}
    p:\**10{.exe,.dll,.zip,.vbs,.gz,.aspx,.php,.rar,.7z}
    o:\**10{.exe,.dll,.zip,.vbs,.gz,.aspx,.php,.rar,.7z}
    n:\**10{.exe,.dll,.zip,.vbs,.gz,.aspx,.php,.rar,.7z}
    m:\**10{.exe,.dll,.zip,.vbs,.gz,.aspx,.php,.rar,.7z}
    l:\**10{.exe,.dll,.zip,.vbs,.gz,.aspx,.php,.rar,.7z}
    k:\**10{.exe,.dll,.zip,.vbs,.gz,.aspx,.php,.rar,.7z}
    j:\**10{.exe,.dll,.zip,.vbs,.gz,.aspx,.php,.rar,.7z}
    i:\**10{.exe,.dll,.zip,.vbs,.gz,.aspx,.php,.rar,.7z}
    h:\**10{.exe,.dll,.zip,.vbs,.gz,.aspx,.php,.rar,.7z}
    g:\**10{.exe,.dll,.zip,.vbs,.gz,.aspx,.php,.rar,.7z}
    f:\**10{.exe,.dll,.zip,.vbs,.gz,.aspx,.php,.rar,.7z}
    e:\**10{.exe,.dll,.zip,.vbs,.gz,.aspx,.php,.rar,.7z}
    d:\**10{.exe,.dll,.zip,.vbs,.gz,.aspx,.php,.rar,.7z}
    c:\**10{.exe,.dll,.zip,.vbs,.gz,.aspx,.php,.rar,.7z}
    b:\**10{.exe,.dll,.zip,.vbs,.gz,.aspx,.php,.rar,.7z}
    a:\**10{.exe,.dll,.zip,.vbs,.gz,.aspx,.php,.rar,.7z}

Conditions |
    Condition type: MODIFICATION_TIME
    Modification time, Min last modified time: 2017-10-26 19:00:00 UTC
Action | STAT
```

The paths are a bit unorthodox because we weren't sure what drives each system has and we wanted to get all of them when the system connected. Now that I think about it a little more, it could have probably been achieved with something like:

{a,b,c,d...}:\**10{.exe,.dll...}

**Comment by grrrrrrrrr** [comment]
The last server deb we released was built on Sept 5, so a few days before we fixed this bug. If you want, you can install one of the nightly builds, they should work fine and not have this bug.

Some feedback for your hunt: What you are trying to do there will put a lot of strain on both the GRR system but also your clients. The FileFinder tries to keep the clients in the dark about what you are searching for and does most of the matching server side. For that, it has to send all directory contents from all machines to the server, a significant amount of data. For a large recursive file system search like this, this is not really efficient.

In general, we recommend against doing those deep file system searches because of the impact on the target systems but if you want to run this hunt, I suggest you use the client side file finder. That flow does all the searching and matching on the client (with the tradeoff of eventually leaking IOCs to a compromised machine, but that doesn't really apply here) and should be somewhere between 10 to 100 times faster than the server side flow for this particular hunt.

**Comment by devyzr** [comment]
Thank you, I'll install the newer version.

Thank you for clearing that aspect of the file finder up! I'll take it into account in future searches.
