### ISSUE TITLE
UpdateClient flow doesn't work on Ubuntu

### ISSUE THREAD

**Issue by atkinsj** [google/grr#720]
Running UpdateClient from Ubuntu fails as the service restarts in the middle of the dpkg -i, killing all child processes leaving the service stopped and non-functional.

```
Jul 02 13:14:56 ubuntu grrd[13119]: (Reading database ... 141574 files and directories currently installed.)
Jul 02 13:14:56 ubuntu systemd[1]: Stopping grr linux amd64...
Jul 02 13:14:56 ubuntu systemd[1]: Stopped grr linux amd64.
```

**Comment by mbushkov** [comment]
@atkinsj, which GRR version of the server and of the client are you using?

**Comment by atkinsj** [comment]
Whoops, sorry, server is 3.3.0.3 trying to update a 3.3.0.0 client to 3.3.0.3.

**Comment by mbushkov** [comment]
Did you see it on a single client or on multiple? I.e. how hard is it to reproduce the issue?

**Comment by atkinsj** [comment]
I've tried it on ~5 hosts so far, all the same behaviour. Operating system is `Ubuntu 18.04.2 LTS`.

**Comment by mbushkov** [comment]
Judging by the code, we do not properly detach the process when running UpdateAgent client action with a DEB ([see](https://github.com/google/grr/blob/master/grr/client/grr_response_client/client_actions/linux/linux.py#L355)). We do, however, detach when doing UpdateAgent with a RPM.

I think we should detach in both cases, otherwise we hit the issue described by @atkinsj above.

**Comment by mbushkov** [comment]
@atkinsj, quick question: did you use UpdateClient on Ubuntu before? The bug in the client code is quite old and should affect a few previous releases.

**Comment by atkinsj** [comment]
Yeah, it’s never worked for me on Ubuntu. Windows hosts seem to crash
during the upgrade and don’t recover until reboot but I haven’t
investigated that to see if it’s just me yet.

**Comment by 0x0BCA** [comment]
We have exactly the same issues with Windows and Ubuntu clients.

**Comment by atkinsj** [comment]
Hey folks, any update on this?

**Comment by mbushkov** [comment]
@atkinsj, my understanding is that the client update mechanism hasn't worked in a long time and it's not clear when it stopped functioning, since it's not tested.

We're looking at prioritising this issue in Q4 and reimplementing/fixing the client update mechanism with adequate testing. If everything goes fine, this will be fixed in December GRR release.

**Comment by clairmont32** [comment]
Looking forward seeing this get fixed in the future!

**Comment by atkinsj** [comment]
Did this make it in to 3.3.0.8?

**Comment by mbushkov** [comment]
@atkinsj, we're still targeting December.

**Comment by mbushkov** [comment]
@atkinsj , we've just released GRR v3.4.0.1 (see https://github.com/google/grr/releases/tag/v3.4.0.1). 

We've fixed a problem with UpdateClient on Ubuntu clients. We also refactored the flow: now instead of specifying deprecated AFF4 path, you have to specify a "binary path" which correspond to paths you see on "Manage Binaries" page (i.e. `linux/installers/grr_3.4.0.1_amd64.deb`).

**Comment by mbushkov** [comment]
Closing the issue for now. Please reopen in case you encounter issues with the clients from the latest release.

**Comment by atkinsj** [comment]
This still isn't resolved for me. I issued an UpdateClient to a 3245 client with a 3401 binary and the client immediately stopped responding and did not call back in until a host reboot, where it called back in as 3245. Results and log tabs are empty. Flow shows:

```

State | CLIENT_CRASHED
-- | --
Status | Client crashed.


```

**Comment by mbushkov** [comment]
The thing is: "UpdateClient" code is executed on the client. This means that v3245 client won't function correctly, since it's an old client and has a bug in the update code. Updating v3401 client to any further version should work though, since in v3401 the issue is fixed.

**Comment by atkinsj** [comment]
Ah gotcha, for some reason I thought this was Python generated server side and pushed to the client. Will update via config management to 3401. Thanks!
